.TH "Error codes" 3 "Sun Mar 22 2015" "Version 1.1" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Error codes \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBOPUS_OK\fP"
.br
.RI "\fINo error\&. \fP"
.ti -1c
.RI "#define \fBOPUS_BAD_ARG\fP"
.br
.RI "\fIOne or more invalid/out of range arguments\&. \fP"
.ti -1c
.RI "#define \fBOPUS_BUFFER_TOO_SMALL\fP"
.br
.RI "\fIThe mode struct passed is invalid\&. \fP"
.ti -1c
.RI "#define \fBOPUS_INTERNAL_ERROR\fP"
.br
.RI "\fIAn internal error was detected\&. \fP"
.ti -1c
.RI "#define \fBOPUS_INVALID_PACKET\fP"
.br
.RI "\fIThe compressed data passed is corrupted\&. \fP"
.ti -1c
.RI "#define \fBOPUS_UNIMPLEMENTED\fP"
.br
.RI "\fIInvalid/unsupported request number\&. \fP"
.ti -1c
.RI "#define \fBOPUS_INVALID_STATE\fP"
.br
.RI "\fIAn encoder or decoder structure is invalid or already freed\&. \fP"
.ti -1c
.RI "#define \fBOPUS_ALLOC_FAIL\fP"
.br
.RI "\fIMemory allocation has failed\&. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBOPUS_ALLOC_FAIL\fP"
.PP
Memory allocation has failed\&. 
.SS "#define \fBOPUS_BAD_ARG\fP"
.PP
One or more invalid/out of range arguments\&. 
.SS "#define \fBOPUS_BUFFER_TOO_SMALL\fP"
.PP
The mode struct passed is invalid\&. 
.SS "#define \fBOPUS_INTERNAL_ERROR\fP"
.PP
An internal error was detected\&. 
.SS "#define \fBOPUS_INVALID_PACKET\fP"
.PP
The compressed data passed is corrupted\&. 
.SS "#define \fBOPUS_INVALID_STATE\fP"
.PP
An encoder or decoder structure is invalid or already freed\&. 
.SS "#define \fBOPUS_OK\fP"
.PP
No error\&. 
.SS "#define \fBOPUS_UNIMPLEMENTED\fP"
.PP
Invalid/unsupported request number\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Opus from the source code\&.
